# Generated by Django 6.0.1 on 2026-01-11 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmpresaModel",
            fields=[
                (
                    "nit",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="NIT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la Empresa"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
            },
        ),
        migrations.CreateModel(
            name="ProductoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=50, unique=True, verbose_name="Código"),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Producto"
                    ),
                ),
                ("caracteristicas", models.TextField(verbose_name="Características")),
                (
                    "precios",
                    models.JSONField(
                        default=dict,
                        help_text="Formato: {'USD': 100, 'COP': 400000}",
                        verbose_name="Precios (Moneda -> Valor)",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="core.empresamodel",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
            },
        ),
    ]
